# -*- coding: utf-8 -*-
"""
准确修复 - 基于实际文件内容
"""
import os

script_dir = os.path.dirname(os.path.abspath(__file__))
app_jsx_path = os.path.join(script_dir, 'frontend', 'src', 'App.jsx')

# 读取文件，保持原始换行符
with open(app_jsx_path, 'r', encoding='utf-8', errors='replace', newline='') as f:
    content = f.read()

# 检测换行符类型
if '\r\n' in content:
    line_ending = '\r\n'
elif '\r' in content:
    line_ending = '\r'
else:
    line_ending = '\n'

print(f"Line ending: {repr(line_ending)}")

lines = content.split(line_ending)
print(f"Total lines: {len(lines)}")

# 找出所有引号不匹配的行
problem_lines = []
for i, line in enumerate(lines):
    if line.strip().startswith('//'):
        continue
    code_part = line.split('//')[0] if '//' in line else line
    
    # 检查单引号是否匹配
    quote_count = code_part.count("'") - code_part.count("\\'")
    
    # 检查是否有乱码
    has_garbled = any(ord(c) >= 0xe000 for c in code_part) or '\ufffd' in code_part
    
    if has_garbled and quote_count % 2 == 1:
        problem_lines.append(i + 1)

print(f"Problem lines: {problem_lines}")

# 定义修复 (行号从1开始 -> 正确的完整行内容)
fixes = {
    285: "            title: session.summary || '新对话',",
    548: "          'counter': '展厅',",
    549: "          'product': '商品部仓库'",
    352: "        if (title === '新对话' || !currentConversationId) {",
    355: "            title = firstUserMessage.content.substring(0, 20) || '新对话'",
    407: "            setConversationTitle(lastConversation.title || '新对话')",
    493: "          setConversationTitle(conversation.title || '新对话')",
    603: "      showToast('加载客户列表失败，请检查网络连接')",
    705: "      console.error('创建收料单失败', error)",
    706: "      alert('创建收料单失败')",
    752: "          const withdrawalMessage = `✅ 提料单已生成\\n\\n📋 单号：${result.withdrawal_no}\\n👤 客户：${customerName}\\n⚖️ 克重：${withdrawalWeight.toFixed(2)} 克${remarkText ? `\\n📝 备注：${remarkText}` : ''}\\n⏰ 时间：${new Date().toLocaleString('zh-CN')}\\n\\n<!-- WITHDRAWAL_ORDER:${result.id}:${result.withdrawal_no} -->`",
    768: "        alert('创建提料单失败：' + (error.detail || '未知错误'))",
    771: "      console.error('创建提料单失败', error)",
    772: "      alert('创建提料单失败')",
    818: "    if (title === '新对话' || !currentConversationId) {",
    821: "        title = firstUserMessage.content.substring(0, 20) || '新对话'",
    931: "        const title = conversation?.title || messages.find(m => m.type === 'user')?.content?.substring(0, 20) || '新对话'",
    993: "    setConversationTitle('新对话')",
    1094: "          throw new Error('响应体为空')",
    1097: "        console.log('开始读取SSE流...')",
    1260: "                    console.log('创建新的系统消息来显示结果')",
    1269: "                        if (data.data.action === '退货') {",
    1271: "                        } else if (data.data.action === '入库') {",
    1273: "                        } else if (data.data.action === '创建销售单') {",
    1316: "                        console.log('收到待确认商品数据，共', allProducts.length, '个商品', allProducts)",
    1330: "                              name: cardData.supplier || '未知供应商',",
    1473: "          console.log('SSE 请求已取消')",
    1486: "        errorMessage = '❌ 无法连接到服务器，请检查后端服务是否运行（http://localhost:8000）'",
    1605: "            `重量：${data.detail.weight}克\\n` +",
    1606: "            `工费：${data.detail.labor_cost}元/克\\n` +",
    1607: "            `供应商：${data.detail.supplier}\\n` +",
    1608: "            `总成本：${data.detail.total_cost.toFixed(2)}元\\n\\n` +",
    1609: "            `📦 当前库存：${data.inventory.total_weight}克`",
    1618: "          systemMessage += `\\n\\n📦 库存信息：\\n` +",
    1619: "            `商品名称：${data.inventory.product_name}\\n` +",
    1620: "            `总重量：${data.inventory.total_weight}克\\n`",
    1624: "          systemMessage += `\\n💵 工费明细：\\n`",
    1626: "            systemMessage += `  记录${idx + 1}：工费${detail.labor_cost.toFixed(2)}元/克，重量${detail.weight}克，总工费${detail.total_cost.toFixed(2)}元（入库单：${detail.order_no}）\\n`",
    1645: "            systemMessage += `${idx + 1}. ${inv.product_name}：${inv.total_weight}克`",
    1647: "              systemMessage += `，最新工费：${inv.latest_labor_cost}元/克`",
    1650: "              systemMessage += `，平均工费：${inv.avg_labor_cost}元/克`",
    1652: "            systemMessage += `\\n`",
    1656: "            systemMessage += `\\n💵 总库存：${data.total_weight.toFixed(2)}克`",
    1667: "          systemMessage += `\\n\\n📋 入库单详情：\\n` +",
    1668: "            `入库单号：${data.order.order_no}\\n` +",
    1669: "            `入库时间：${new Date(data.order.create_time).toLocaleString('zh-CN')}\\n` +",
    1670: "            `状态：${data.order.status}\\n\\n` +",
    1671: "            `商品明细：\\n`",
    1673: "            systemMessage += `${idx + 1}. ${detail.product_category || detail.product_name}：${detail.weight}克，工费${detail.labor_cost}元/克，总工费${detail.total_cost.toFixed(2)}元\\n`",
    1684: "          systemMessage += `\\n\\n📋 最近的入库单：\\n`",
    1698: "          systemMessage += `\\n\\n📋 销售单信息：\\n` +",
    1699: "            `销售单号：${data.order.order_no}\\n` +",
    1700: "            `客户：${data.order.customer_name}\\n` +",
    1701: "            `业务员：${data.order.salesperson}\\n` +",
    1702: "            `门店代码：${data.order.store_code || '未填写'}\\n` +",
    1703: "            `日期：${new Date(data.order.order_date).toLocaleString('zh-CN')}\\n` +",
    1704: "            `状态：${data.order.status}\\n\\n` +",
    1705: "            `商品明细：\\n`",
    1709: "              systemMessage += `${idx + 1}. ${detail.product_name}：${detail.weight}克，工费${detail.labor_cost}元/克，总工费${detail.total_labor_cost.toFixed(2)}元\\n`",
    1713: "          systemMessage += `\\n💵 合计：\\n` +",
    1714: "            `总克重：${data.order.total_weight}克\\n` +",
    1715: "            `总工费：${data.order.total_labor_cost.toFixed(2)}元`",
    1725: "          systemMessage += `\\n\\n📋 销售单列表：\\n`",
    1738: "          systemMessage += `\\n\\n👤 客户信息：\\n` +",
    1739: "            `客户编号：${data.customer.customer_no}\\n` +",
    1740: "            `客户名称：${data.customer.name}\\n` +",
    1741: "            `电话：${data.customer.phone || '未填写'}\\n` +",
    1742: "            `类型：${data.customer.customer_type}\\n` +",
    1743: "            `累计购买：${data.customer.total_purchase_amount.toFixed(2)}元\\n` +",
    1744: "            `购买次数：${data.customer.total_purchase_count}次`",
    1753: "          systemMessage += `\\n\\n👤 客户列表：\\n` +",
    1754: "            `共 ${data.customers.length} 位客户\\n\\n`",
    1767: "          systemMessage += `\\n\\n❌ 库存检查失败：\\n`",
    1825: "          errorMessage += `\\n\\n❌ 缺失的必填项：\\n`",
    1827: "            errorMessage += `  • ${field}\\n`",
    1829: "          errorMessage += `\\n请补充完整信息后重新提交。`",
    1834: "            errorMessage += `\\n\\n📋 系统规则提醒：\\n`",
    1835: "            errorMessage += `每张入库单只能对应一个供应商。如果一次入库包含多个供应商的商品，请按供应商拆分为多张入库单分别提交。\\n`",
    1836: "            errorMessage += `例如：先提交\"供应商A的商品1、商品2\"，再提交\"供应商B的商品3、商品4\"。`",
    1926: "        let systemMessage = \"✅ 图片识别完成！\\n\\n\"",
    1930: "          systemMessage += \"💡 处理过程：\\n\" + data.thinking_steps.join('\\n') + \"\\n\\n\"",
    1933: "        systemMessage += \"📝 识别出的文字内容已显示在编辑对话框中，请仔细审核并编辑。\"",
    1944: "          errorMessage = \"💡 处理过程：\\n\" + data.thinking_steps.join('\\n') + \"\\n\\n\" + errorMessage",
    1951: "          errorMessage += `\\n\\n📝 已识别出部分文字（已显示在编辑对话框中），您可以手动修正后确认入库。`",
    1961: "      let errorMessage = `❌ 上传失败：${error.message}`",
    1967: "        errorMessage = '❌ 上传超时，请检查网络连接或稍后重试'",
    1993: "        alert('请输入内容')",
    2055: "              `  工费：${detail.labor_cost}元/克\\n` +",
    2056: "              `  供应商：${detail.supplier}\\n` +",
    2057: "              `  该商品工费：${detail.total_cost.toFixed(2)}元\\n\\n`",
    2060: "          systemMessage += `💵 合计工费：${data.total_labor_cost.toFixed(2)}元\\n\\n`",
    2063: "            systemMessage += `📦 库存更新：\\n`",
    2065: "              systemMessage += `  ${inv.product_name}：${inv.total_weight}克\\n`",
    2076: "          systemMessage += `\\n\\n📋 销售单信息：\\n` +",
    2077: "            `销售单号：${data.order.order_no}\\n` +",
    2078: "            `客户：${data.order.customer_name}\\n` +",
    2079: "            `业务员：${data.order.salesperson}\\n` +",
    2081: "            `日期：${new Date(data.order.order_date).toLocaleString('zh-CN')}\\n` +",
    2082: "            `状态：${data.order.status}\\n\\n` +",
    2083: "            `商品明细：\\n`",
    2087: "              systemMessage += `${idx + 1}. ${detail.product_name}：${detail.weight}克，工费${detail.labor_cost}元/克，总工费${detail.total_labor_cost.toFixed(2)}元\\n`",
    2091: "          systemMessage += `\\n💵 合计：\\n` +",
    2092: "            `总克重：${data.order.total_weight}克\\n` +",
    2093: "            `总工费：${data.order.total_labor_cost.toFixed(2)}元`",
    2103: "          systemMessage += `\\n\\n📦 商品列表：\\n`",
    2105: "            systemMessage += `${idx + 1}. ${inv.product_name}：${inv.total_weight}克`",
    2107: "              systemMessage += `，最新工费：${inv.latest_labor_cost}元/克`",
    2110: "              systemMessage += `，平均工费：${inv.avg_labor_cost.toFixed(2)}元/克`",
    2112: "            systemMessage += `\\n`",
    2116: "            systemMessage += `\\n💵 总库存：${data.total_weight.toFixed(2)}克`",
    2422: '                  title="销售管理"',
    2425: "                  <span>销售管理</span>",
    2456: "                      <span>仪表盘</span>",
    2469: "                        <span>数据分析</span>",
    2478: "                        <span>数据导出</span>",
    2491: "                      <span>业务员管理</span>",
    2673: "                        if (hour < 12) return '上午好！有什么可以帮您的？'",
    2674: "                        if (hour < 14) return '中午好！记得休息一下 🍵'",
    2675: "                        if (hour < 18) return '下午好！我随时准备为您服务'",
    2676: "                        return '晚上好！辛苦了 🌙'",
    2687: '                      <button onClick={() => setInput(\'帮我开一张销售单\')} className=\"px-3 py-1.5 text-sm bg-blue-50 text-blue-600 rounded-full hover:bg-blue-100 transition-colors\">开销售单</button>',
    2689: '                      <button onClick={() => setInput(\'库存还有多少\')} className=\"px-3 py-1.5 text-sm bg-blue-50 text-blue-600 rounded-full hover:bg-blue-100 transition-colors\">查库存</button>',
    2694: '                      <button onClick={() => setInput(\'古法黄金戒指 100克 工费6元 供应商金源珠宝 帮我入库\')} className=\"px-3 py-1.5 text-sm bg-orange-50 text-orange-600 rounded-full hover:bg-orange-100 transition-colors\">入库商品</button>',
    2695: '                      <button onClick={() => setInput(\'查询今天的入库单\')} className=\"px-3 py-1.5 text-sm bg-orange-50 text-orange-600 rounded-full hover:bg-orange-100 transition-colors\">今日入库</button>',
    2696: '                      <button onClick={() => setInput(\'库存分析\')} className=\"px-3 py-1.5 text-sm bg-orange-50 text-orange-600 rounded-full hover:bg-orange-100 transition-colors\">库存分析</button>',
    2701: '                      <button onClick={() => setInput(\'查看今天待结算的订单\')} className=\"px-3 py-1.5 text-sm bg-green-50 text-green-600 rounded-full hover:bg-green-100 transition-colors\">待结算</button>',
    2702: '                      <button onClick={() => setInput(\'张老板提5克\')} className=\"px-3 py-1.5 text-sm bg-green-50 text-green-600 rounded-full hover:bg-green-100 transition-colors\">客户提料</button>',
    2703: '                      <button onClick={() => setInput(\'收料登记\')} className=\"px-3 py-1.5 text-sm bg-green-50 text-green-600 rounded-full hover:bg-green-100 transition-colors\">收料登记</button>',
    2708: '                      <button onClick={() => setInput(\'查看本月财务对账情况\')} className=\"px-3 py-1.5 text-sm bg-purple-50 text-purple-600 rounded-full hover:bg-purple-100 transition-colors\">月度对账</button>',
    2721: '                      <button onClick={() => setInput(\'查看今日金料收付情况\')} className=\"px-3 py-1.5 text-sm bg-yellow-50 text-yellow-600 rounded-full hover:bg-yellow-100 transition-colors\">今日收付</button>',
    2722: '                      <button onClick={() => setInput(\'金料库存统计\')} className=\"px-3 py-1.5 text-sm bg-yellow-50 text-yellow-600 rounded-full hover:bg-yellow-100 transition-colors\">库存统计</button>',
    2728: '                      <button onClick={() => setInput(\'本月业绩分析\')} className=\"px-3 py-1.5 text-sm bg-red-50 text-red-600 rounded-full hover:bg-red-100 transition-colors\">业绩分析</button>',
    2729: '                      <button onClick={() => setInput(\'库存预警\')} className=\"px-3 py-1.5 text-sm bg-red-50 text-red-600 rounded-full hover:bg-red-100 transition-colors\">库存预警</button>',
    2750: '                      <div className=\"text-2xl mb-3\">📝</div>',
    2751: '                      <h3 className=\"font-semibold text-gray-900 mb-2\">快速开单</h3>',
    2752: '                      <p className=\"text-sm text-gray-600\">创建销售单</p>',
    2762: '                      <div className=\"text-2xl mb-3\">📦</div>',
    2763: '                      <h3 className=\"font-semibold text-gray-900 mb-2\">接收库存</h3>',
    2764: '                      <p className=\"text-sm text-gray-600\">接收从仓库转移的商品</p>',
    2774: '                      <div className=\"text-2xl mb-3\">📦</div>',
    2775: '                      <h3 className=\"font-semibold text-gray-900 mb-2\">快捷入库</h3>',
    2776: '                      <p className=\"text-sm text-gray-600\">表格形式批量入库</p>',
    2786: '                      <div className=\"text-2xl mb-3\">📊</div>',
    2787: '                      <h3 className=\"font-semibold text-gray-900 mb-2\">分仓库存</h3>',
    2788: '                      <p className=\"text-sm text-gray-600\">管理仓库库存和转移</p>',
    2798: '                      <div className=\"text-2xl mb-3\">🔄</div>',
    2799: '                      <h3 className=\"font-semibold text-gray-900 mb-2\">快捷退货</h3>',
    2800: '                      <p className=\"text-sm text-gray-600\">快速创建退货单（退给供应商）</p>',
    2810: '                      <div className=\"text-2xl mb-3\">🔄</div>',
    2811: '                      <h3 className=\"font-semibold text-gray-900 mb-2\">快捷退货</h3>',
    2812: '                      <p className=\"text-sm text-gray-600\">快速创建退货单（退给商品部）</p>',
    2822: '                      <div className=\"text-2xl mb-3\">📋</div>',
    2823: '                      <h3 className=\"font-semibold text-gray-900 mb-2\">待结算订单</h3>',
    2824: '                      <p className=\"text-sm text-gray-600\">查看待结算的销售单</p>',
    2834: '                      <div className=\"text-2xl mb-3\">👥</div>',
    2835: '                      <h3 className=\"font-semibold text-gray-900 mb-2\">',
    2836: "                        {userRole === 'sales' ? '客户查询' : '客户管理'}",
    2841: "                          : '管理客户信息'}",
    2852: '                      <div className=\"text-2xl mb-3\">💵</div>',
    2853: '                      <h3 className=\"font-semibold text-gray-900 mb-2\">财务对账</h3>',
    2854: '                      <p className=\"text-sm text-gray-600\">查看财务对账情况</p>',
    2864: '                      <div className=\"text-2xl mb-3\">🏢</div>',
    2865: '                      <h3 className=\"font-semibold text-gray-900 mb-2\">供应商管理</h3>',
    2866: '                      <p className=\"text-sm text-gray-600\">管理供应商信息</p>',
    2876: '                      <div className=\"text-2xl mb-3\">📈</div>',
    2877: '                      <h3 className=\"font-semibold text-gray-900 mb-2\">数据仪表盘</h3>',
    2878: '                      <p className=\"text-sm text-gray-600\">今日销售、业绩排行</p>',
    2888: '                      <div className=\"text-2xl mb-3\">📊</div>',
    2889: '                      <h3 className=\"font-semibold text-gray-900 mb-2\">数据分析</h3>',
    2890: '                      <p className=\"text-sm text-gray-600\">查看业务数据分析</p>',
    2900: '                      <div className=\"text-2xl mb-3\">📥</div>',
    2901: '                      <h3 className=\"font-semibold text-gray-900 mb-2\">数据导出</h3>',
    2902: '                      <p className=\"text-sm text-gray-600\">导出各类数据报表</p>',
    2912: '                      <div className=\"text-2xl mb-3\">⚖️</div>',
    2913: '                      <h3 className=\"font-semibold text-gray-900 mb-2\">金料管理</h3>',
    2914: '                      <p className=\"text-sm text-gray-600\">金料台账、收料、付料</p>',
    2924: '                      <div className=\"text-2xl mb-3\">🏷️</div>',
    2925: '                      <h3 className=\"font-semibold text-gray-900 mb-2\">商品编码</h3>',
    2926: '                      <p className=\"text-sm text-gray-600\">管理F编码、FL编码</p>',
    2939: '                      <div className=\"text-2xl mb-3\">📝</div>',
    2940: '                      <h3 className=\"font-semibold text-gray-900 mb-2\">创建付料单</h3>',
    2941: '                      <p className=\"text-sm text-gray-600\">支付供应商金料</p>',
    3012: "                            <span className=\"text-orange-600 font-bold text-lg\">{pd.customer?.name?.charAt(0) || '客'}</span>",
    3031: '                            <span className=\"text-gray-600\">收款后欠款</span>',
    3035: "                                : `-¥${Math.abs(pd.balance_after || 0).toFixed(2)} (预收款)`",
    3043: '                          <span>收款方式：</span>',
    3118: "                              <span className=\"text-yellow-600 font-bold text-lg\">{rd.customer?.name?.charAt(0) || '客'}</span>",
    3129: '                            <span className=\"text-gray-600\">收料克重</span>',
    3130: '                            <span className=\"font-bold text-yellow-700 text-2xl\">{rd.gold_weight?.toFixed(2)} 克</span>',
    3133: '                            <span className=\"text-gray-600\">成色</span>',
    3138: '                              <span className=\"text-gray-600\">备注</span>',
    3129: '                            <span className=\"text-gray-600\">收料克重</span>',
    3130: "                            <span className=\"font-bold text-yellow-700 text-2xl\">{rd.gold_weight?.toFixed(2)} 克</span>",
    3133: '                            <span className=\"text-gray-600\">成色</span>',
    3138: '                              <span className=\"text-gray-600\">备注</span>',
    3213: '                            <span className=\"font-semibold\">确认创建收料单</span>',
    3222: "                              <span className=\"text-blue-600 font-bold text-lg\">{wd.customer?.name?.charAt(0) || '客'}</span>",
    3233: '                            <span className=\"text-gray-600\">提料克重</span>',
    3234: '                            <span className=\"font-bold text-blue-700 text-2xl\">{wd.gold_weight?.toFixed(2)} 克</span>',
    3237: '                            <span className=\"text-gray-600\">当前存料</span>',
    3238: '                            <span className=\"font-medium text-gray-900\">{wd.current_balance?.toFixed(2)} 克</span>',
    3241: '                            <span className=\"text-gray-600\">提料后余额</span>',
    3242: '                            <span className=\"font-medium text-green-600\">{wd.balance_after?.toFixed(2)} 克</span>',
    3246: '                              <span className=\"text-gray-600\">备注</span>',
    3268: "                                    remark: wd.remark || '聊天提料'",
    3276: "                                      ? { ...m, type: 'system', content: `✅ 提料单创建成功！\\n\\n单号：${result.withdrawal_no}\\n客户：${wd.customer.name}\\n克重：${wd.gold_weight.toFixed(2)}克\\n（待料部确认发出）` }",
    3285: "                                  alert('提料单创建失败：' + (error.detail || '未知错误'))",
    3288: "                              console.error('提料单创建失败', error)",
    3289: "                              alert('提料单创建失败：' + error.message)",
    3339: "                              <span className=\"text-green-600 font-bold text-lg\">{wd.customer_name?.charAt(0) || '客'}</span>",
    3350: '                            <span className=\"text-gray-600\">提料克重</span>',
    3351: '                            <span className=\"font-bold text-green-700 text-2xl\">{wd.gold_weight?.toFixed(2)} 克</span>',
    3355: '                              <span className=\"text-gray-600\">备注</span>',
    1757: "            systemMessage += `${idx + 1}. ${customer.name} (${customer.customer_no}) - ${customer.phone || '无电话'} - 累计购买${customer.total_purchase_amount.toFixed(2)}元\\n`",
    1850: "        errorMessage = '❌ 无法连接到服务器，请检查后端服务是否运行（http://localhost:8000）'",
    1880: "        content: '❌ 图片文件过大，请上传小于10MB的图片'",
    1965: "        errorMessage = '❌ 无法连接到服务器，请检查后端服务是否运行（http://localhost:8000）'",
    2080: "            `门店代码：${data.order.store_code || '未填写'}\\n` +",
    2672: "                        if (hour < 9) return '早上好！今天也要加油哦 ☀️'",
    2688: '                      <button onClick={() => setInput(\'查询今天的销售情况\')} className="px-3 py-1.5 text-sm bg-blue-50 text-blue-600 rounded-full hover:bg-blue-100 transition-colors">今日销售</button>',
    2709: '                      <button onClick={() => setInput(\'今日收款汇总\')} className="px-3 py-1.5 text-sm bg-purple-50 text-purple-600 rounded-full hover:bg-purple-100 transition-colors">收款汇总</button>',
    2714: '                      <button onClick={() => setInput(\'帮我查询张三今天的销售情况\')} className="px-3 py-1.5 text-sm bg-indigo-50 text-indigo-600 rounded-full hover:bg-indigo-100 transition-colors">客户销售</button>',
    2715: '                      <button onClick={() => setInput(\'王五有多少欠款\')} className="px-3 py-1.5 text-sm bg-indigo-50 text-indigo-600 rounded-full hover:bg-indigo-100 transition-colors">欠款查询</button>',
    2716: '                      <button onClick={() => setInput(\'查询退货记录\')} className="px-3 py-1.5 text-sm bg-indigo-50 text-indigo-600 rounded-full hover:bg-indigo-100 transition-colors">退货记录</button>',
    2727: '                      <button onClick={() => setInput(\'查看今日销售数据汇总\')} className="px-3 py-1.5 text-sm bg-red-50 text-red-600 rounded-full hover:bg-red-100 transition-colors">今日汇总</button>',
    2840: "                          ? '查询客户销售、退货、欠款、往来账目' ",
    3070: "                                  alert('收款登记失败：' + (result.error || '未知错误'))",
    3074: "                                alert('收款登记失败：' + error.message)",
    3612: "                                    if (!confirm('确定要撤销此结算单吗？撤销后可以重新选择支付方式进行结算。')) return",
    3624: "                                        alert('撤销失败：' + (error.detail || '未知错误'))",
    3627: "                                        console.error('撤销结算单失败', error)",
    3628: "                                        alert('撤销失败：' + error.message)",
    3704: '                          <th className=\"px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider\">序号</th>',
    3705: '                          <th className=\"px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider\">工费（元/克）</th>',
    3706: '                          <th className=\"px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider\">重量（克）</th>',
    3707: '                          <th className=\"px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider\">总工费（元）</th>',
    3708: '                          <th className=\"px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider\">入库单号</th>',
    3709: '                          <th className=\"px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider\">入库时间</th>',
    3798: "                                      return { ...m, inboundCard: updateCard(card, { status: 'error', errorMessage: errorReason || '数据报错已提交' }) }",
    3803: "                                  console.error('报错提交失败:', error)",
    3699: '                  <h3 className=\"text-lg font-semibold mb-2\">工费明细表</h3>',
    3883: "                                              errorMessage: errorReason || '数据报错已提交' ",
    3891: "                                      console.error('报错提交失败:', error)",
    3971: '                              <span className=\"text-gray-600\">销售单号：</span>',
    3975: '                              <span className=\"text-gray-600\">客户：</span>',
    3979: '                              <span className=\"text-gray-600\">业务员：</span>',
    3983: '                              <span className=\"text-gray-600\">门店代码：</span>',
    3987: '                              <span className=\"text-gray-600\">日期：</span>',
    3991: '                              <span className=\"text-gray-600\">状态：</span>',
    3993: "                                msg.salesOrder.status === '已结算' ? 'text-green-600' : ",
    3994: "                                msg.salesOrder.status === '待结算' ? 'text-yellow-600' : ",
    4009: '                                      <th className=\"px-4 py-2 text-left text-xs font-medium text-gray-700 uppercase\">商品名称</th>',
    4010: '                                      <th className=\"px-4 py-2 text-left text-xs font-medium text-gray-700 uppercase\">克重</th>',
    4011: '                                      <th className=\"px-4 py-2 text-left text-xs font-medium text-gray-700 uppercase\">工费</th>',
    4012: '                                      <th className=\"px-4 py-2 text-left text-xs font-medium text-gray-700 uppercase\">总工费</th>',
    4019: '                                        <td className=\"px-4 py-2 text-sm text-gray-900\">{detail.weight}克</td>',
    4020: '                                        <td className=\"px-4 py-2 text-sm text-gray-900\">{detail.labor_cost}元/克</td>',
    4021: '                                        <td className=\"px-4 py-2 text-sm font-semibold text-gray-900\">{detail.total_labor_cost.toFixed(2)}元</td>',
    4028: '                                <span>总克重：<span className=\"text-blue-600\">{msg.salesOrder.total_weight}克</span></span>',
    4029: '                                <span>总工费：<span className=\"text-green-600\">{msg.salesOrder.total_labor_cost.toFixed(2)}元</span></span>',
    4049: '                                    <span className=\"text-red-600 font-medium\">错误：</span>',
    4053: '                                    <span className=\"text-gray-600\">需要：</span>',
    4054: '                                    <span className=\"ml-2 font-semibold\">{error.required_weight}克</span>',
    4057: '                                    <span className=\"text-gray-600\">可用：</span>',
    4058: '                                    <span className=\"ml-2 font-semibold text-red-600\">{error.available_weight}克</span>',
    4062: '                                      <span className=\"text-gray-600\">已预留：</span>',
    4063: '                                      <span className=\"ml-2 font-semibold\">{error.reserved_weight}克</span>',
    4068: '                                      <span className=\"text-gray-600\">总库存：</span>',
    4069: '                                      <span className=\"ml-2 font-semibold\">{error.total_weight}克</span>',
    4040: "                          <h3 className=\"text-xl font-bold text-red-800 mb-4\">❌ 库存检查失败</h3>",
    4096: "                                        text: msg.chartTitle || '趋势分析（折线图）',",
    4115: "                                          if (msg.chartType === '供应商分析' || msg.chartType === '生成图表') {",
    4116: "                                            return '供应商占比分析（柱状图）'",
    4117: "                                          } else if (msg.chartType === '查询库存') {",
    4118: "                                            return '📊 库存统计图表'",
    4120: "                                          return '数据统计图表'",
    4129: "                              const unit = label.includes('工费') ? ' 元' : ' 克';",
    4138: "                                          title: { display: true, text: '重量（克）' }",
    4141: "                                          title: { display: true, text: '商品名称' }",
    4161: "                                            if (msg.chartType === '供应商分析' || msg.chartType === '生成图表') {",
    4162: "                                              return '🍪 供应商占比分布'",
    4164: "                                            return '🍪 库存占比分布'",
    4190: '                                <span>📊 查看详细数据</span>',
    4198: '                                        <th className=\"px-3 py-2 text-left font-medium text-gray-600\">供应商</th>',
    4199: '                                        <th className=\"px-3 py-2 text-right font-medium text-gray-600\">供货重量(克)</th>',
    4200: '                                        <th className=\"px-3 py-2 text-right font-medium text-gray-600\">总工费(元)</th>',
    4201: '                                        <th className=\"px-3 py-2 text-right font-medium text-gray-600\">供货次数</th>',
    4221: '                                        <th className=\"px-3 py-2 text-left font-medium text-gray-600\">商品名称</th>',
    4222: '                                        <th className=\"px-3 py-2 text-right font-medium text-gray-600\">库存重量(克)</th>',
    4223: '                                        <th className=\"px-3 py-2 text-right font-medium text-gray-600\">入库次数</th>',
    2684: '                  <span className=\"text-gray-400 text-sm\">💡 试试：</span>',
    4337: '                    ⚠️ 请检查并编辑识别内容，确认无误后点击"确认入库"',
    4340: '                    <li>检查商品名称是否正确</li>',
    4341: '                    <li>检查重量、工费、供应商等信息</li>',
    4342: '                    <li>可以手动编辑修改内容</li>',
    4352: '                    placeholder=\"识别出的文字内容将显示在这里...\"',
    4450: '                  title=\"快捷退货\"',
    4452: '                  ↩️ 退货',
    4456: '          {/* 图片上传按钮 */}',
    4412: '                  title=\"快捷入库\"',
    4414: '                  📦 入库',
    4418: '              {/* 快速开单按钮 - 仅柜台可见（结算专员不需要） */}',
    4431: '                  title=\"快速开单\"',
    4433: '                  📝 开单',
    4437: '              {/* 快捷退货按钮 - 商品专员和柜台可见 */}',
    4481: '          {/* 快捷收料/提料按钮 - 结算专员和管理层可见 */}',
    4487: "                title={currentLanguage === 'en' ? 'Quick Receipt' : '快捷收料'}",
    4489: "                📦 {t('chat.receipt')}",
    4494: "                title={currentLanguage === 'en' ? 'Quick Withdrawal' : '快捷提料'}",
    4478: "                {uploading ? `📲 ${t('chat.scanning')}` : `📲 ${t('chat.scan')}`}",
    4496: "                ⬆️ {t('chat.withdrawal')}",
    4468: "            title=\"OCR识别入库单据 - 支持拍照或上传单据图片自动识别\"",
    4562: "              // 结算单确认后，在聊天框显示明细",
    4564: "                  `${idx + 1}. ${item.product_name}：${item.weight}克 × ¥${item.labor_cost}/克 = ¥${item.total_labor_cost.toFixed(2)}`",
    4567: "                const paymentMethodStr = data.payment_method === 'cash_price' ? '结价' : ",
    4568: "                          data.payment_method === 'mixed' ? '混合支付' : '结料'",
    4570: "                const settlementMessage = `✅ **结算单确认成功**",
    4572: "📋 **结算单号**：${data.settlement_no}",
    4573: "👤 **客户**：${data.customer_name}",
    4574: "🧑‍💼 **业务员**：${data.salesperson}",
    4575: "💸 **支付方式**：${paymentMethodStr}",
    4577: "📦 **商品明细**：",
    4580: "📊 **汇总**：",
    4581: "- 总克重：${data.total_weight.toFixed(2)}克",
    4582: "- 工费合计：¥${data.labor_amount.toFixed(2)}",
    4583: "${data.gold_price ? `- 金价：${data.gold_price.toFixed(2)} 元/克` : ''}",
    4584: "${data.material_amount > 0 ? `- 金料金额：¥${data.material_amount.toFixed(2)}` : ''}",
    4585: "- **应收总计：¥${data.total_amount.toFixed(2)}**",
    4774: "            // Build inbound message content (with hidden ID marker for history print button)",
    4776: "              let info = `  - ${p.name}: ${p.weight}g (labor \\u00A5${p.labor_cost}/g)`",
    4780: "                info += ` [${pieceCount}件 件工费¥${pieceLaborCost}]`",
    4784: "            const moreProducts = result.products.length > 5 ? `\\n  ... 等共 ${result.products.length} 件商品` : ''",
    4785: "            // 只在有多件商品时显示件数，单件只显示克重",
    4786: "            const countInfo = result.total_count > 1 ? `\\n📦 入库数量：${result.total_count} 件` : ''",
    4789: "            // 添加到聊天记录显示（包含入库单信息，用于下载/打印）",
    4768: "      {/* 快捷入库弹窗 - 需要入库权限 */}",
    4761: "              console.error('Save return record to chat history failed:', error)",
    4730: "              }).catch(err => console.error('Save sales message failed:', err))",
    4736: "      {/* 快捷退货弹窗 - 商品专员和柜台可用 */}",
    4742: "            // Build return success message content (with hidden ID marker for history print button)",
    4743: "            const returnMessage = `\\u2705 **退货单创建成功**\\n\\n\\uD83D\\uDCCB 单号：${result.return_no}\\n\\uD83D\\uDCE6 商品数量：${result.item_count}个\\n\\u2696\\uFE0F 总退货克重：${result.total_weight?.toFixed(2) || 0}克\\n\\uD83D\\uDCB5 总工费：\\u00A5${result.total_labor_cost?.toFixed(2) || 0}\\n\\uD83D\\uDCDD 退货原因：${result.return_reason}${result.supplier_name ? `\\n\\uD83C\\uDFED 供应商：${result.supplier_name}` : ''}${result.from_location_name ? `\\n\\uD83D\\uDCCD 发起位置：${result.from_location_name}` : ''}\\n\\n<!-- RETURN_ORDER:${result.return_id}:${result.return_no} -->`",
    4745: "            // Add to chat history display (includes return order info for download/print)",
    4755: "            // Save to backend chat history (with ID marker)",
    4757: "              await fetch(`${API_BASE_URL}/api/chat-logs/message?session_id=${encodeURIComponent(currentSessionId)}&message_type=assistant&content=${encodeURIComponent(returnMessage)}&user_role=${userRole}&intent=return`, {",
    4928: '                  <button type=\"button\" onClick={() => setShowQuickReceiptModal(false)} className=\"flex-1 px-4 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50\">取消</button>',
    4929: '                  <button type=\"submit\" className=\"flex-1 px-4 py-2 bg-yellow-500 text-white rounded-lg hover:bg-yellow-600\">确认并打印</button>',
    4888: "                      已选择：{quickFormCustomers.find(c => c.id.toString() === quickReceiptForm.customer_id)?.name}",
    4981: "                      已选择：{quickFormCustomers.find(c => c.id.toString() === quickWithdrawalForm.customer_id)?.name}",
    2416: "              {/* 销售管理按钮 - 柜台、结算、业务可见 */}",
    2429: "              {/* 语言切换按钮 */}",
    2440: "                <span className=\"text-base\">{currentLanguage === 'zh' ? '🇨🇳' : '🇺🇸'}</span>",
    2441: "                <span>{currentLanguage === 'zh' ? '中文' : 'EN'}</span>",
    2444: "              {/* 导航按钮 */}",
    2447: "                  {/* 仪表盘按钮 - 管理层快速查看 */}",
    2459: "                  {/* 数据分析按钮 - 使用权限检查 */}",
    2482: "                  {/* 业务员管理按钮 - 使用权限检查 */}",
    2494: "                  {/* 分仓库存按钮 - 柜台(接收) + 商品专员(转移) + 管理层 */}",
    2503: "                      {/* 待处理转移单数量badge */}",
    2513: "                  {/* 结算管理按钮 - 使用权限检查 */}",
    2522: "                      {/* 待结算销售单数量badge */}",
    2532: "                  {/* 快捷开单按钮 - 使用权限检查 */}",
    2544: "                  {/* 客户管理按钮 - 使用权限检查(查看或管理权限) */}",
    2555: "                  {/* 供应商管理按钮 - 使用权限检查 */}",
    2566: "                  {/* 退货管理按钮 - 使用权限检查 */}",
    2577: "                  {/* 金料管理按钮 - 料部和管理层可见 */}",
    2588: "                  {/* 暂借管理按钮 - 结算专员和管理层可见 */}",
    2599: "                  {/* 商品编码按钮 - 商品专员和管理层可见 */}",
    2610: "                  {/* 入库单据按钮 - 商品专员和管理层可见 */}",
    2621: "                  {/* 财务对账按钮 - 使用权限检查 */}",
    2632: "                  {/* 历史回溯按钮 - 所有角色都可用 */}",
    2657: "        {/* 主内容区域 - 根据 currentPage 切换 */}",
    2660: "            {/* 对话区域 - 苹果风格 */}",
    2665: "                {/* 智能时间问候 + AI标识 */}",
    2682: "                {/* 智能快捷建议按钮 - 可点击直接发送 */}",
    # console语句乱码修复
    316: "        console.log('Backend sync history failed (does not affect usage):', error.message)",
    320: "    // Cache local data",
    408: "            console.log('[Role Switch] Restore last conversation:', lastSessionId)",
    494: "          console.log('[Restore] Restored from local:', savedSessionId, 'message count:', restoredMessages.length)",
    497: "          console.log('[Restore] No local data, try to sync from backend:', savedSessionId)",
    512: "                console.log('[Restore] Restored from backend:', savedSessionId, 'message count:', parsedMessages.length)",
    516: "            console.error('[Restore] Backend sync failed:', backendError)",
    520: "        console.error('[Restore] Restore conversation failed:', error)",
    524: "          console.warn('[Restore] Cleared corrupted history records')",
    563: "      console.error('Load pending transfer count failed:', error)",
    582: "      console.error('Load pending sales count failed:', error)",
    593: "        console.log('Load customer list:', data)  // Debug log",
    598: "        console.error('Load customer list API failed:', response.status)",
    602: "      console.error('Load customer list failed:', error)",
    643: "      console.error('Query customer balance failed:', error)",
    968: "      console.error('Load conversation failed, try to load from local:', error)",
    1055: "      console.log('Send stream request to:', API_ENDPOINTS.CHAT_STREAM)",
    1056: "      console.log('Request message:', userMessage)",
    1078: "      console.log('Received response, status code:', response.status)",
    1079: "      console.log('Response headers:', {",
    1087: "        console.error('Response error, status code:', response.status)",
    1088: "        console.error('Error content:', errorText)",
    1093: "        console.error('Response body is empty')",
    1097: "        console.log('Start reading SSE stream...')",
    1118: "            console.log(`SSE stream ended, total ${chunkCount} data chunks received`)",
    1124: "            console.warn('Received empty value, continue waiting...')",
    1130: "            console.log(`Received chunk #${chunkCount}, length: ${value.length} bytes`)",
    1142: "                      console.log('Parse SSE JSON:', jsonStr)",
    1144: "                      console.log('Received SSE data:', data)",
    1147: "                        console.log('[IMPORTANT] Detected all_products:', data.data.all_products)",
    1212: "                console.log('Received payment_confirm event:', data)",
    1253: "                console.log('Received complete event:', data)",
    1260: "                    console.log('Create new system message to display result')",
    1266: "                      console.log('Detected need_form flag, popup corresponding form:', data.data.action)",
    1295: "                    console.log('Create message, content:', messageContent)",
    1301: "                    console.log('[Inbound Debug] Complete data.data:', JSON.stringify(data.data, null, 2))",
    1302: "                    console.log('[Inbound Debug] all_products exists:', 'all_products' in (data.data || {}))",
    1303: "                    console.log('[Inbound Debug] all_products value:', data.data?.all_products)",
    1304: "                    console.log('[Inbound Debug] all_products length:', data.data?.all_products?.length)",
    1310: "                        console.log('[Debug] data.data.all_products original:', data.data.all_products)",
    1311: "                        console.log('[Debug] data.data.card_data original:', data.data.card_data)",
    1320: "                          console.log(`[Debug] Create card ${index+1}:`, cardData)",
    1339: "                        console.log('Create inbound cards, total:', inboundCards.length, inboundCards)",
    1347: "                        console.error('Create inbound cards failed:', error)",
    1351: "                      console.log('Detected confirmed inbound data (backward compatible)')",
    1365: "                          console.log('Create confirmed inbound card (backward compatible):', inboundCard)",
    1367: "                          console.error('Create inbound card failed:', error)",
    1371: "                      console.log('No match for inbound card condition, data:', data.data)",
    1394: "                    console.warn('complete event has no data field')",
    1397: "                  console.log('Update existing content message')",
    1433: "                            console.error('Create inbound card failed:', error)",
    1455: "                console.error('Parse SSE data failed:', e)",
    1460: "          console.error('Read SSE stream failed:', readError)",
    1473: "          console.log('SSE request cancelled')",
    3738: "                                console.log('Confirm inbound:', card)",
    3754: "                                  console.log('Confirm inbound result:', result)",
    3755: "                                  console.log('Order ID:', result.order?.id)",
    3756: "                                  console.log('Order No:', result.order?.order_no)",
    3767: "                                      console.log('Updated card:', updatedCard)",
    3768: "                                      console.log('Updated orderId:', updatedCard.orderId)",
    3774: "                                  console.error('Confirm inbound failed:', error)",
    3792: "                                console.log('Report inbound data error:', card, errorReason)",
    3824: "                                    console.log('Confirm single product inbound:', cardToConfirm)",
    3841: "                                      console.log('Confirm inbound result:', result)",
    3859: "                                      console.error('Confirm inbound failed:', error)",
    3875: "                                    console.log('Report inbound data error:', cardToReport, errorReason)",
    3903: "                                  console.log('Batch confirm inbound')",
    3939: "                                      console.error('Batch inbound failed:', error)",
    4606: "                  }).catch(err => console.error('Save settlement message failed:', err))",
    4805: "              console.error('Save inbound record to chat history failed:', error)",
    3073: "                                console.error('Receipt registration failed:', error)",
    3177: "                                console.error('Receipt order creation failed:', error)",
    3984: '                              <span className="font-semibold">{msg.salesOrder.store_code || \'未填写\'}</span>',
    4787: "            const inboundMessage = `✅ **入库成功**${result.order_no ? `\\n\\n📋 单号：${result.order_no}` : ''}\\n🏪 供应商：${result.supplier_name || '未指定'}${countInfo}\\n⚖️ 总克重：${result.total_weight.toFixed(2)}克\\n💵 总工费：¥${result.total_labor_cost.toFixed(2)}\\n\\n📋 商品明细：\\n${productList}${moreProducts}${result.order_id ? `\\n\\n<!-- INBOUND_ORDER:${result.order_id}:${result.order_no} -->` : ''}`",
}

# 应用修复
fixed_count = 0
for line_num, new_content in fixes.items():
    idx = line_num - 1
    if 0 <= idx < len(lines):
        lines[idx] = new_content
        fixed_count += 1
        print(f"Fixed line {line_num}")

print(f"\nTotal fixed: {fixed_count} lines")

# 用原始换行符重新组合
content = line_ending.join(lines)

# 写回文件
with open(app_jsx_path, 'w', encoding='utf-8', newline='') as f:
    f.write(content)

print("File saved!")

# 验证行数
with open(app_jsx_path, 'r', encoding='utf-8', errors='replace') as f:
    verify_lines = f.readlines()
print(f"Verify: {len(verify_lines)} lines")
